apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patches:
  - deployment.yaml 
images:
  - name: ygazzah2/vote
    newTag: main-e448b031-1753293010 # {"$imagepolicy": "flux-system:vote:tag"}
